networks:
  confluence-network:
    external: true

volumes:
  confluence-data:
  confluence-postgres:
  confluence-postgres-backup:
  confluence-data-backups:
  confluence-database-backups:

services:
  postgres:
    image: postgres:15.10
    volumes:
      - confluence-postgres:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: confluencedb
      POSTGRES_USER: confluencedbuser
      POSTGRES_PASSWORD: nQOqvLkOJzWD82QcMiUm
    networks:
      - confluence-network
    healthcheck:
      test: [ "CMD", "pg_isready", "-q", "-d", "confluencedb", "-U", "confluencedbuser" ]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 60s
    restart: unless-stopped

  confluence:
    image: atlassian/confluence-server:9.0.0-m30-ubuntu
    volumes:
      - confluence-data:/var/atlassian/application-data/confluence
    environment:
      JVM_MINIMUM_MEMORY: 8G
      JVM_MAXIMUM_MEMORY: 8G
      ATL_DB_TYPE: postgresql
      ATL_DB_DRIVER: org.postgresql.Driver
      ATL_JDBC_USER: confluencedbuser
      ATL_JDBC_PASSWORD: nQOqvLkOJzWD82QcMiUm
      ATL_JDBC_URL: jdbc:postgresql://postgres:5432/confluencedb
    networks:
      - confluence-network
    healthcheck:
      test: ["CMD", "nc", "-z", "localhost", "8090"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 90s
    restart: unless-stopped
    depends_on:
      postgres:
        condition: service_healthy

  backups:
    image: postgres:15.10
    command: >-
      sh -c 'sleep 30m
      while true; do
        pg_dump -h postgres -p 5432 -d confluencedb -U confluencedbuser | gzip > /src/confluence-postgres/backups/confluence-postgres-backup-$$(date "+%Y-%m-%d_%H-%M").gz 
        && tar -zcpf /srv/confluence-application-data/backups/confluence-application-data-backup-$$(date "+%Y-%m-%d_%H-%M").tar.gz /var/atlassian/application-data/confluence 
        && find /srv/confluence-postgres/backups -type f -mtime +30 | xargs rm -f 
        && find /srv/confluence-application-data/backups -type f -mtime +30 | xargs rm -f;
        sleep 24h; done'
    volumes:
      - confluence-postgres-backup:/srv/confluence-postgres/backups
      - confluence-data:/var/atlassian/application-data/confluence
      - confluence-data-backups:/srv/confluence-application-data/backups
      - confluence-database-backups:/srv/confluence-database/backups

    environment:
      CONFLUENCE_DB_NAME: confluencedb
      CONFLUENCE_DB_USER: confluencedbuser
      PGPASSWORD: nQOqvLkOJzWD82QcMiUm
      BACKUP_INIT_SLEEP: 30m
      BACKUP_INTERVAL: 24h
      POSTGRES_BACKUP_PRUNE_DAYS: 30
      DATA_BACKUP_PRUNE_DAYS: 30
      POSTGRES_BACKUPS_PATH: /srv/confluence-postgres/backups
      DATA_BACKUPS_PATH: /srv/confluence-application-data/backups
      DATA_PATH: /var/atlassian/application-data/confluence
      POSTGRES_BACKUP_NAME: confluence-postgres-backup
      DATA_BACKUP_NAME: confluence-application-data-backup
    networks:
      - confluence-network
    restart: unless-stopped
    depends_on:
      postgres:
        condition: service_healthy

  nginx:
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - ./ssl:/etc/nginx/ssl:ro
    ports:
      - "80:80"
      - "443:443"
    networks:
      - confluence-network
    depends_on:
      confluence:
        condition: service_healthy
    restart: unless-stopped
    
